Updated help file, improved error code returning

diff --git a/sv/syn/RUN_VECTOR b/sv/syn/RUN_VECTOR
--- a/sv/syn/RUN_VECTOR
+++ b/sv/syn/RUN_VECTOR
@@ -11,9 +11,34 @@ set host=`hostname`
 set hind="hind.ecs.soton.ac.uk"
 set hart="hart.ecs.soton.ac.uk"
 
+if ("$1" == "--help" || "$1" == "-h") then
+    echo "This script is used to run test vector generation and testing for the scan path.\
+          It must be called in the following format:\
+          ./RUN_VECTOR {"opt" | "basic"} {clock period} ["pnr"]\
+          where {} signify compulsary arguments.\
+          \
+          opt          - This specifies performing place and route on a synthesis/place and route that had opt set.\
+          basic        - This specifies performing place and route on a synthesis/place and route that had basic set.\
+          clock period - Specify here the integer value used as the clock period for synthesis/place and route.\
+          pnr          - Specify this optional flag if you wish to perform this script on the netlist generated by\
+                         place and route. Default is to use netlist generated by synthesis.\
+          "
+    exit
+endif
+
 if ($host != $hind && $host != $hart) then
     echo "Error: Vector Testing requires hind or hart CAD server for tools. Exiting..."
-    exit
+    exit 1
+endif
+
+if ("$1" != "opt" && "$1" != "basic") then
+    echo "Error: Incorrect arguments given. See --help information."
+    exit 1
+endif
+
+if ("$2" != "[0-9]+") then
+    echo "Error: Incorrect arguments given. See --help information."
+    exit 1
 endif
 
 if (${3} == "pnr") then
