Disabled regex number check. Needs fixinggit add RUN_SYN RUN_PNR RUN_VECTOR

diff --git a/sv/syn/RUN_PNR b/sv/syn/RUN_PNR
--- a/sv/syn/RUN_PNR
+++ b/sv/syn/RUN_PNR
@@ -28,10 +28,10 @@ if ($host != $hind && $host != $hart) then
     exit 1
 endif
 
-if ("$1" != "opt" && "$1" != "basic") then
-    echo "Error: Incorrect arguments given. See --help information."
-    exit 1
-endif
+#if ("$1" != "opt" && "$1" != "basic") then
+#    echo "Error: Incorrect arguments given. See --help information."
+#    exit 1
+#endif
 
 if ("$2" != "[0-9]+") then
     echo "Error: Incorrect arguments given. See --help information."
diff --git a/sv/syn/RUN_VECTOR b/sv/syn/RUN_VECTOR
--- a/sv/syn/RUN_VECTOR
+++ b/sv/syn/RUN_VECTOR
@@ -36,10 +36,10 @@ if ("$1" != "opt" && "$1" != "basic") then
     exit 1
 endif
 
-if ("$2" != "[0-9]+") then
-    echo "Error: Incorrect arguments given. See --help information."
-    exit 1
-endif
+#if ("$2" != "[0-9]+") then
+#    echo "Error: Incorrect arguments given. See --help information."
+#    exit 1
+#endif
 
 if (${3} == "pnr") then
     echo "Using PNR";
